name: CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout repo
      with:
       fetch-depth: 0

    - uses: qcastel/github-actions-maven/actions/maven@master
    - name: Maven build	
      run: mvn clean install
