name: CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0

    - name: Maven build	
    - uses: qcastel/github-actions-maven/actions/maven@master
      with:
        maven-args: "clean install"
